import { PresetScene } from '../types.ts';
import mangaImg from '../assets/images/preset_manga_japanese_1790429251274.jpg';
import gameImg from '../assets/images/preset_game_jrpg_1790429263368.jpg';
import scifiImg from '../assets/images/preset_scifi_hud_1790429276327.jpg';
import menuImg from '../assets/images/preset_tokyo_menu_1790429289868.jpg';

export const PRESET_SCENES: PresetScene[] = [
  {
    id: 'manga-action',
    title: 'มังงะญี่ปุ่น (Shonen Action Manga)',
    categoryName: 'มังงะ/การ์ตูน',
    description: 'หน้าการ์ตูนญี่ปุ่นลายเส้นหมึกดำ บทพูดแนวแอ็กชัน-แฟนตาซี พร้อมบอลลูนคำพูดแนวตั้งและเสียงเอฟเฟกต์ (SFX)',
    imagePath: mangaImg,
    sourceLanguage: 'Japanese',
    recommendedTone: 'manga',
    initialResult: {
      timestamp: Date.now(),
      detected_source_language: 'Japanese (ภาษาญี่ปุ่น)',
      overall_summary_thai: 'ตัวเอกยืนอยู่หน้าประตูดินแดนเวทมนตร์โบราณที่กำลังเปิดออก พร้อมประกาศความมุ่งมั่นที่จะก้าวข้ามขีดจำกัดของตนเอง',
      items: [
        {
          id: 'manga-1',
          box_2d: [80, 680, 240, 890],
          original_text: 'ついに封印の扉が開かれた…！',
          translated_thai: 'ในที่สุด... ประตูผนึกโบราณก็เปิดออกแล้ว!',
          category: 'dialogue',
          reading_direction: 'vertical',
          confidence: 0.98,
          bg_theme: 'bubble',
        },
        {
          id: 'manga-2',
          box_2d: [120, 110, 310, 340],
          original_text: 'この力を手に入れれば、世界を取り戻せるのか？',
          translated_thai: 'หากข้าได้พลังนี้มา... จะช่วยกอบกู้โลกใบนี้คืนมาได้จริงหรือ?',
          category: 'dialogue',
          reading_direction: 'vertical',
          confidence: 0.97,
          bg_theme: 'bubble',
        },
        {
          id: 'manga-3',
          box_2d: [380, 420, 520, 610],
          original_text: 'ゴゴゴゴゴ… (SFX)',
          translated_thai: '*ครืนนนนน... (เสียงมิติสั่นสะเทือน)*',
          category: 'sfx',
          reading_direction: 'vertical',
          confidence: 0.94,
          bg_theme: 'bubble',
        },
        {
          id: 'manga-4',
          box_2d: [620, 180, 780, 460],
          original_text: '待っていろ、必ずお前を救い出す！',
          translated_thai: 'รอข้าก่อนเถอะ... ข้าจะช่วยเจ้าออกมาให้ได้แน่นอน!',
          category: 'dialogue',
          reading_direction: 'vertical',
          confidence: 0.99,
          bg_theme: 'bubble',
        },
        {
          id: 'manga-5',
          box_2d: [790, 660, 930, 910],
          original_text: '運命の歯車が今、動き始める！',
          translated_thai: 'กงล้อแห่งโชคชะตา บัดนี้ได้เริ่มหมุนแล้ว!',
          category: 'narration',
          reading_direction: 'vertical',
          confidence: 0.96,
          bg_theme: 'bubble',
        },
      ],
    },
  },
  {
    id: 'game-jrpg',
    title: 'เกม RPG ภาษาญี่ปุ่น (JRPG Dialogue)',
    categoryName: 'เกม & บทสนทนา',
    description: 'ฉากเกมผจญภัยแนวแฟนตาซี พร้อมกล่องข้อความสนทนาตัวละคร (Dialogue Box) และข้อมูลเควส',
    imagePath: gameImg,
    sourceLanguage: 'Japanese',
    recommendedTone: 'gaming',
    initialResult: {
      timestamp: Date.now(),
      detected_source_language: 'Japanese (ภาษาญี่ปุ่น)',
      overall_summary_thai: 'อัศวินหนุ่มสนทนากับสหายร่วมรบ ณ โบราณสถานศักดิ์สิทธิ์ เตือนให้ระวังกับดักและมอนสเตอร์ที่ซ่อนอยู่ในเงามืด',
      items: [
        {
          id: 'game-1',
          box_2d: [40, 50, 110, 310],
          original_text: 'QUEST: 古代の遺跡を探索せよ',
          translated_thai: 'เควส: สำรวจซากโบราณสถานยุคดึกดำบรรพ์',
          category: 'ui',
          reading_direction: 'horizontal',
          confidence: 0.99,
          bg_theme: 'dark',
        },
        {
          id: 'game-2',
          box_2d: [690, 70, 760, 240],
          original_text: 'レオン (Leon)',
          translated_thai: 'เลออน (Leon)',
          category: 'heading',
          reading_direction: 'horizontal',
          confidence: 0.99,
          bg_theme: 'dark',
        },
        {
          id: 'game-3',
          box_2d: [760, 80, 930, 920],
          original_text: '油断するなよ。この先に眠る守護者は、かつての聖戦を生き延びた古の兵器だ。準備を整えてから進もう。',
          translated_thai: 'อย่าประมาทเด็ดขาดนะ... ผู้พิทักษ์ที่หลับใหลอยู่เบื้องหน้า คืออาวุธโบราณที่รอดมาจากมหาสงครามศักดิ์สิทธิ์ เตรียมความพร้อมให้ดีก่อนก้าวต่อไป!',
          category: 'dialogue',
          reading_direction: 'horizontal',
          confidence: 0.98,
          bg_theme: 'dark',
        },
        {
          id: 'game-4',
          box_2d: [40, 760, 100, 950],
          original_text: 'HP: 1,450 / 1,450 | MP: 320',
          translated_thai: 'พลังชีวิต: 1,450 / 1,450 | มานา: 320',
          category: 'ui',
          reading_direction: 'horizontal',
          confidence: 0.96,
          bg_theme: 'dark',
        },
      ],
    },
  },
  {
    id: 'scifi-hud',
    title: 'ไซเบอร์พังก์ HUD & เควสเกม (Sci-Fi UI)',
    categoryName: 'อินเตอร์เฟสเกม/ซอฟต์แวร์',
    description: 'หน้าจอโฮโลกราฟิกแจ้งเตือนภารกิจ ค่าสถิติยุทธวิธี และบันทึกข้อความทางทหาร',
    imagePath: scifiImg,
    sourceLanguage: 'English',
    recommendedTone: 'gaming',
    initialResult: {
      timestamp: Date.now(),
      detected_source_language: 'English (ภาษาอังกฤษ)',
      overall_summary_thai: 'ระบบยุทธวิธีตรวจพบความผิดปกติของโครงข่ายพลังงาน พร้อมคำสั่งให้เข้าแทรกแซงและกู้คืนแกนควบคุมก่อนระบบล่ม',
      items: [
        {
          id: 'scifi-1',
          box_2d: [70, 70, 160, 480],
          original_text: 'TACTICAL HUD: GRID OVERLOAD DETECTED',
          translated_thai: 'ระบบยุทธวิธี: ตรวจพบโครงข่ายพลังงานทำงานเกินพิกัด!',
          category: 'heading',
          reading_direction: 'horizontal',
          confidence: 0.99,
          bg_theme: 'dark',
        },
        {
          id: 'scifi-2',
          box_2d: [200, 70, 390, 470],
          original_text: 'MISSION OBJECTIVE: Infiltrate Sector 7 Sub-Core and extract the encrypted memory drive before lockdown.',
          translated_thai: 'เป้าหมายภารกิจ: ลอบแทรกซึมเข้าไปยังซับคอร์เซกเตอร์ 7 และดึงไดรฟ์ข้อมูลความจำที่เข้ารหัสออกมาก่อนระบบสั่งล็อกดาวน์',
          category: 'ui',
          reading_direction: 'horizontal',
          confidence: 0.97,
          bg_theme: 'dark',
        },
        {
          id: 'scifi-3',
          box_2d: [430, 70, 560, 460],
          original_text: 'SHIELD INTEGRITY: 88% | AMMO: 240/300',
          translated_thai: 'ความเสถียรของเกราะ: 88% | กระสุน: 240/300',
          category: 'ui',
          reading_direction: 'horizontal',
          confidence: 0.98,
          bg_theme: 'dark',
        },
        {
          id: 'scifi-4',
          box_2d: [720, 530, 890, 930],
          original_text: 'WARNING: Hostile cybernetic units converging on your sector. Threat level: CRITICAL.',
          translated_thai: 'คำเตือน: ยูนิตไซบอร์กฝ่ายศัตรูกำลังรุมล้อมเข้ามาในเซกเตอร์ของคุณ ระดับภัยคุกคาม: วิกฤตขั้นรุนแรง!',
          category: 'dialogue',
          reading_direction: 'horizontal',
          confidence: 0.99,
          bg_theme: 'dark',
        },
      ],
    },
  },
  {
    id: 'tokyo-menu',
    title: 'ป้ายเมนูร้านอาหารญี่ปุ่น (Tokyo Izakaya Menu)',
    categoryName: 'ป้าย & เอกสารในชีวิตจริง',
    description: 'ป้ายกระดานไม้หน้าร้านอิซากายะในโตเกียว ตัวอักษรคันจิบอกชื่ออาหารและราคาเงินเยน',
    imagePath: menuImg,
    sourceLanguage: 'Japanese',
    recommendedTone: 'general',
    initialResult: {
      timestamp: Date.now(),
      detected_source_language: 'Japanese (ภาษาญี่ปุ่น)',
      overall_summary_thai: 'รายการเมนูอาหารขึ้นชื่อของร้านราเมนและอิซากายะ เช่น ราเมนซุปกระดูกหมูเข้มข้น หมูชาชูย่างถ่าน และเกี๊ยวซ่ากระทะร้อน',
      items: [
        {
          id: 'menu-1',
          box_2d: [120, 200, 270, 780],
          original_text: '特製 濃厚豚骨らーめん (980円)',
          translated_thai: 'เมนูพิเศษ: ทงคัตสึราเมนซุปกระดูกหมูสูตรเข้มข้น (980 เยน)',
          category: 'heading',
          reading_direction: 'horizontal',
          confidence: 0.98,
          bg_theme: 'bubble',
        },
        {
          id: 'menu-2',
          box_2d: [310, 180, 460, 810],
          original_text: '自家製 炙りチャーシュー盛り合わせ (650円)',
          translated_thai: 'หมูชาชูย่างไฟสูตรโฮมเมดจานรวม (650 เยน)',
          category: 'dialogue',
          reading_direction: 'horizontal',
          confidence: 0.97,
          bg_theme: 'bubble',
        },
        {
          id: 'menu-3',
          box_2d: [500, 200, 640, 780],
          original_text: 'パリパリ焼き餃子 6個 (450円)',
          translated_thai: 'เกี๊ยวซ่ากระทะร้อน แป้งกรอบไส้แน่น 6 ชิ้น (450 เยน)',
          category: 'dialogue',
          reading_direction: 'horizontal',
          confidence: 0.99,
          bg_theme: 'bubble',
        },
        {
          id: 'menu-4',
          box_2d: [680, 220, 820, 770],
          original_text: '生ビール (アサヒ スーパードライ) (500円)',
          translated_thai: 'เบียร์สด อาซาฮี ซูเปอร์ดราย (500 เยน)',
          category: 'dialogue',
          reading_direction: 'horizontal',
          confidence: 0.98,
          bg_theme: 'bubble',
        },
      ],
    },
  },
];
